/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { JobListingService } from "../jobListing.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { JobListingCreateInput } from "./JobListingCreateInput";
import { JobListing } from "./JobListing";
import { JobListingFindManyArgs } from "./JobListingFindManyArgs";
import { JobListingWhereUniqueInput } from "./JobListingWhereUniqueInput";
import { JobListingUpdateInput } from "./JobListingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class JobListingControllerBase {
  constructor(
    protected readonly service: JobListingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: JobListing })
  @nestAccessControl.UseRoles({
    resource: "JobListing",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createJobListing(
    @common.Body() data: JobListingCreateInput
  ): Promise<JobListing> {
    return await this.service.createJobListing({
      data: data,
      select: {
        companyName: true,
        createdAt: true,
        description: true,
        documents: true,
        id: true,
        position: true,
        postedBy: true,
        qualifications: true,
        salary: true,
        skills: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [JobListing] })
  @ApiNestedQuery(JobListingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "JobListing",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async jobListings(@common.Req() request: Request): Promise<JobListing[]> {
    const args = plainToClass(JobListingFindManyArgs, request.query);
    return this.service.jobListings({
      ...args,
      select: {
        companyName: true,
        createdAt: true,
        description: true,
        documents: true,
        id: true,
        position: true,
        postedBy: true,
        qualifications: true,
        salary: true,
        skills: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: JobListing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobListing",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async jobListing(
    @common.Param() params: JobListingWhereUniqueInput
  ): Promise<JobListing | null> {
    const result = await this.service.jobListing({
      where: params,
      select: {
        companyName: true,
        createdAt: true,
        description: true,
        documents: true,
        id: true,
        position: true,
        postedBy: true,
        qualifications: true,
        salary: true,
        skills: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: JobListing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobListing",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateJobListing(
    @common.Param() params: JobListingWhereUniqueInput,
    @common.Body() data: JobListingUpdateInput
  ): Promise<JobListing | null> {
    try {
      return await this.service.updateJobListing({
        where: params,
        data: data,
        select: {
          companyName: true,
          createdAt: true,
          description: true,
          documents: true,
          id: true,
          position: true,
          postedBy: true,
          qualifications: true,
          salary: true,
          skills: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: JobListing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "JobListing",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteJobListing(
    @common.Param() params: JobListingWhereUniqueInput
  ): Promise<JobListing | null> {
    try {
      return await this.service.deleteJobListing({
        where: params,
        select: {
          companyName: true,
          createdAt: true,
          description: true,
          documents: true,
          id: true,
          position: true,
          postedBy: true,
          qualifications: true,
          salary: true,
          skills: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
